---
title: The effect of (glucose) and inflammation on drug-metabolizing enzymes and transporters in a novel 3D model of primary human hepatocytes
authors:
  - name: Norah Jones
    affiliation: The University
    roles: writing
    corresponding: true
bibliography: references.bib
---

## Abstract

Drug therapy continues to be a pivotal element in the treatment of a myriad of medical conditions, and pharmacology has come a long way since its early days with empirical treatments with herbalism and has evolved into a sophisticated science. This transformative journey encapsulates the integration of knowledge spanning from molecular biology to large-scale human trials, reflecting the deepening understanding of drug action and biological system interactions.

Despite these advancements, variability in drug efficacy and safety continues to pose significant challenges and is also under the influence of pathological states such as inflammation. The research presented in this thesis delves into the intricate relationship between inflammation and drug metabolism, focusing on the modulation of drug-metabolizing enzymes within a novel 3D model of primary human hepatocytes.

In the **first study** we wanted to investigate if the implementation of a novel 3D model of primary human hepatocytes could help bridge the gap of correlation between *in vivo* and *in vitro* research and improve translation of *in vivo* research on this area. A lack of correlation likely due to inherent limitations with the use of the gold standard 2D model, which is inherently prone to rapid dedifferentiation, and the use of supraphysiological concentrations of cytokines. With the hope that the 3D model and the use of also more relevant concentrations of proinflammatory cytokines we found…

The **second study** addresses the critical aspect of selecting suitable reference genes for relative gene expression using qPCR analysis, a key step in ensuring the accuracy and reliability of gene expression analysis. Historically, certain genes have been used indiscriminately as reference genes, under the assumption of their stable expression across different conditions due to their 'housekeeping' function. However, it has become clear that no single gene can or should be universally used as a reference gene, as the lack of stability of your reference gene under your experimental conditions may have a major impact on the final result. Interestingly, we found that most of our chosen genes remained relatively stable under our experimental conditions. This stability is likely attributed to the careful selection of genes that are minimally affected by cytokine treatments or alterations in glucose, ensuring their expression remains consistent, and due to uniformity of genetic expression in a primary human single cell line.

In the **third study**, our approach further refines the 3D model by introducing Kupffer cells, thereby aiming to replicate the hepatic microenvironment more accurately. This enhancement is expected to simulate a more authentic human inflammatory response. By incorporating resident hepatic macrophages, we anticipate a closer mimicry of in vivo cytokine profiles and ratios, enabling a better understanding of the liver's response to inflammation. This advancement marks a significant step towards creating more reliable and representative in vitro models for studying drug metabolism in inflammatory conditions.
